### ISSUE TITLE
rusk-wallet unstake

### ISSUE THREAD

**Issue by sdohuajia** [dusk-network/docs-public#2]
**Describe the bug**.

error: Found argument 'unstake' which wasn't expected, or isn't valid in this context

USAGE:
    rusk-wallet [OPTIONS] [SUBCOMMAND]

For more information try --help

**To Reproduce**
if applicable add a *minimum reproducible example*

```
// Be exhaustive
// 
```

**Expected behaviour**
An error occurred while executing cancellation of pledge

**Logs/Screenshot**
If applicable, add damning logs

![微信图片_20241015213428](https://github.com/user-attachments/assets/22be28ca-10e2-4a34-860d-ce0afbfd4d24)

**Platform**
Fill as appropriate
Linux

**Additional context**

**Comment by HDauven** [comment]
We've [unified](https://github.com/dusk-network/rusk/pull/2683) all commands related to Phoenix and Moonlight. These operations should work with the latest version of Rusk wallet and target the first public address. If you want to target any other address, you'll need to use the `--address` flag as follows:
```bash
rusk-wallet unstake --address <ADDRESS>
```
